[package]
name = "web_previewer"
version = "0.1.0"
edition = "2021"

[dependencies]
previewer = { path = "../previewer" }
image = { workspace = true }
axum = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
