[package]
name = "cli_previewer"
version = "0.1.0"
edition = "2021"

[dependencies]
previewer = { path = "../previewer"}
image = { workspace = true }
clap = { version = "4.5.27", features = ["derive"] }
